### PR TITLE
chore(pipeline): remove siao mapping

### PR DESCRIPTION
**Pull request by hlecuyer**

### CODE REVIEW

**Comment by vmttn** [comment]
1. il reste des mentions à la source `data-inclusion` dans `pipeline/dbt/models/marts/opendata/opendata_***.sql`
2. il faut retirer la variable d'env `AIRFLOW_VAR_DI_EXTRA_STRUCTURES_FILE_UR` dans  `pipeline/defaults.env`
3. `feat(core):` -> `feat(pipeline):`
4. il reste des mentions aux données du siao : 

```bash
~/src/github.com/betagouv/data-inclusion (hlecuyer/feat/siao/remove-intermediate-models)$ git grep -i siao
api/tests/e2e/api/__snapshots__/test_inclusion_data.ambr:            "siao",
api/tests/e2e/api/test_inclusion_data.py:    response = api_client.get(url, params={"source": "siao"})
deployment/docker-compose.yml:    AIRFLOW_VAR_SIAO_FILE_URL: ${AIRFLOW_VAR_SIAO_FILE_URL}
deployment/main.tf:    AIRFLOW_VAR_SIAO_FILE_URL='${var.siao_file_url}'
deployment/template.terraform.tfvars.json:    "siao_file_url": null,
deployment/variables.tf:variable "siao_file_url" {
deployment/variables.tf:  description = "Public URL to the siao export on our s3 bucket"
pipeline/dags/dag_utils/sources/__init__.py:    "siao": {
pipeline/dags/dag_utils/sources/__init__.py:                "url": Variable.get("SIAO_FILE_URL", None),
pipeline/dbt/models/_sources.yml:  - name: siao
pipeline/dbt/models/_sources.yml:    schema: siao
pipeline/dbt/models/marts/opendata/opendata_structures.sql:    WHERE structures.source NOT IN ('soliguide', 'siao', 'finess', 'agefiph')
pipeline/dbt/models/staging/sources/siao/_siao__models.yml:  - name: stg_siao__etablissements
pipeline/dbt/models/staging/sources/siao/stg_siao__etablissements.sql:    {{ stg_source_header('siao', 'etablissements') }}
pipeline/dbt/seeds/schema/labels_nationaux.csv:siao,SIAO,
pipeline/defaults.env:AIRFLOW_VAR_SIAO_FILE_URL=
```

**Comment by vmttn** [comment]
ok ;)

finalement on va retirer complètement le siao (cf le fil de commentaires sur la carte notion)

**Review by vmttn — CHANGES_REQUESTED** [review]
lgtm, il reste juste ce truc à retirer :
```bash
git grep -i inclusion pipeline/
...
pipeline/dbt/models/_sources.yml:  - name: data_inclusion
pipeline/dbt/models/_sources.yml:    schema: data_inclusion
pipeline/dbt/models/_sources.yml:        description: Entered by the data.inclusion team.
pipeline/dbt/models/_sources.yml:        description: Entered by the data.inclusion team.
pipeline/dbt/models/_sources.yml:  - name: emplois_de_linclusion
pipeline/dbt/models/_sources.yml:    schema: emplois_de_linclusion
...
```

**Comment by hlecuyer** [comment]
sql```
DROP TABLE public_intermediate_tmp.int_data_inclusion__adresses;
DROP TABLE public_intermediate_tmp.int_data_inclusion__services;
DROP TABLE public_intermediate_tmp.int_data_inclusion__structures;
DROP TABLE public_intermediate_tmp.int_siao__adresses;
DROP TABLE public_intermediate_tmp.int_siao__structures;

DROP TABLE public_intermediate.int_data_inclusion__adresses;
DROP TABLE public_intermediate.int_data_inclusion__services;
DROP TABLE public_intermediate.int_data_inclusion__structures;
DROP TABLE public_intermediate.int_siao__adresses;
DROP TABLE public_intermediate.int_siao__structures;

DROP VIEW public_staging.stg_data_inclusion__services;
DROP VIEW public_staging.stg_siao__etablissements;

DROP SCHEMA siao;
DROP SCHEMA data_inclusion;
```

**Comment by vmttn** [comment]
un petit rebase pour squash les commits et on est bon ! @hlecuyer

**Pull request merged**
